---
- name: Configurate horde
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ item.dst }}'
    mode: '0644'
    group: "{{ item.group | default('www-data') }}"
  loop: '{{ horde_templates_list }}'
  notify: Restart services

- name: Remove default apache2 configs
  ansible.builtin.file:
    dest: /etc/apache2/{{ item }}
    state: absent
  loop:
    - sites-available/000-default.conf
    - sites-enabled/000-default.conf
    - sites-available/default-ssl.conf
    - sites-enabled/default-ssl.conf
    - conf-available/php-horde.conf
    - conf-enabled/php-horde.conf
  notify: Restart apache2

- name: Ensure log directory exist
  ansible.builtin.file:
    path: '{{ horde_log_path }}'
    state: directory
    mode: '0750'

- name: Activate apache2_modules
  community.general.apache2_module:
    name: '{{ item }}'
    state: present
  loop: '{{ horde_apache2modules }}'
  become: true

- name: Manual apache2 restart
  ansible.builtin.service:
    name: apache2
    state: restarted

- name: Activate webmail
  ansible.builtin.command:
    cmd: a2ensite webmail
  args:
    creates: /etc/apache2/sites-enabled/webmail.conf
  notify: Restart apache2
  changed_when: false
