- name: Setup database
  include_role:
    name: mariadb
  vars:
    mariadb_databases: 
      - name: "{{ horde_db_name }}"
    mariadb_users: 
      - { name: "{{ horde_db_user }}", password: "{{ horde_db_pass }}" }

- name: Install required apt packages
  package:
    name: "{{ horde_apt_packages }}"
    state: present

- name: Install required pip packages
  pip:
    name: "{{ horde_pip_packages }}"

- name: Run webmail install
  expect:
  args:
    command: webmail-install
    responses:
      (.*)What database backend should we use?(.*): "{{ horde_webmail_db_backend }}"
      (.*)Username to connect to the database as(.*): "{{ horde_webmail_user }}"
      (.*)Password to connect with(.*): "{{ horde_webmail_pass }}"
      (.*)How should we connect to the database?(.*): "{{ horde_webmail_db_connect }}"
      (.*)Location of UNIX socket(.*): "{{ horde_webmail_unix_socket }}"
      (.*)Database name to use(.*): "{{ horde_webmail_db_name }}"
      (.*)Internally used charset(.*): "{{ horde_webmail_db_charset }}"
      (.*)Use SSL to connect to the server?(.*): "{{ horde_webmail_ssl }}"
      (.*)Split reads to a different server?(.*): "{{ horde_webmail_split_reads }}"
      (.*)Should Horde log all queries.(.*): "{{ horde_webmail_log }}"
      (.*)(optional)(.*): "{{ horde_webmail_existing_email_to_admin }}"
    echo: yes
  register: expect_webmail_install_result
  failed_when: "expect_webmail_install_result.rc != 0 and 'Thank you for using Horde Groupware Webmail Edition!' not in expect_webmail_install_result.stdout"
  ignore_errors: yes
  become: yes

- name: Remove mnemo config
  file:
    path: "/etc/horde/mnemo/conf.php"
    state: absent

- name: Configurate horde
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    group: "{{ item.group | default('www-data') }}"
  loop: "{{ horde_templates_list }}"
  notify: "restart all"

- name: Activate rewrite
  apache2_module:
    name: rewrite
    state: present
