---
- name: Setup database
  include_role:
    name: mariadb
  vars:
    mariadb_databases:
      - name: "{{ horde_db_name }}"
    mariadb_users:
      - {
        name: "{{ horde_db_user }}",
        password: "{{ horde_db_pass }}",
        privileges: "{{ horde_db_name }}.*:ALL,GRANT"
        }

- name: Install required apt packages
  package:
    name: "{{ horde_apt_packages }}"
    state: present

- name: Install required pip packages
  pip:
    name: "{{ horde_pip_packages }}"

- name: Run webmail install
  expect:
  args:
    command: webmail-install
    responses: "{{ horde_webinstall_responses }}"
    echo: true
  register: expect_webmail_install_result
  failed_when: "expect_webmail_install_result.rc != 0 and 'Thank you for using Horde Groupware Webmail Edition!' not in expect_webmail_install_result.stdout"
  become: true

- name: Configurate horde
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    group: "{{ item.group | default('www-data') }}"
  loop: "{{ horde_templates_list }}"
  notify: restart all

# Enable HTTPS
- name: Copy certificate
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  loop: "{{ horde_certificate }}"

- name: Remove default apache2 configs
  file: dest="/etc/apache2/{{ item }}" state=absent
  loop:
    - sites-available/000-default.conf
    - sites-enabled/000-default.conf
    - sites-available/default-ssl.conf
    - sites-enabled/default-ssl.conf
    - conf-available/php-horde.conf
    - conf-enabled/php-horde.conf
  notify: restart apache2

- name: Ensure log directory exist
  file:
    path: "{{ horde_log_path }}"
    state: directory
    mode: 0750

- name: Activate apache2_modules
  apache2_module:
    name: "{{ item }}"
    state: present
  loop: "{{ horde_apache2modules }}"
  become: true

- name: Manual apache2 restart
  service:
    name: apache2
    state: restarted

- name: Activate webmail
  command: a2ensite webmail
  args:
    creates: /etc/apache2/sites-enabled/webmail.conf
  notify: restart apache2
