---
- name: Restart apache2
  ansible.builtin.service:
    name: apache2
    state: restarted

- name: Restart services
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop: "{{ horde_services }}"
